### PR TITLE
Test actual gitpages version jekyll 3.3.0 and sitemap 0.12.1

### PR DESCRIPTION
**Pull request by carlosdelfino**
I am currently doing a revision in the translation and I still receive
error messages from jekyll-sitemap as in the attached image, I solved the
problem by locking the version of Jekyll in 3.3 so I could use the plugin
for sitemap in version 0.12.1.

I would suggest to test the site in the versions suggested in the link:
https://pages.github.com/versions/,

I am already running 3.3.0 with no problems, but I am still making some
adjustments since with the uOS site I am having a Jekyll crash at startup.

### CODE REVIEW

**Comment by ilg-ul** [comment]
> I would suggest to test the site in the versions suggested in the link: https://pages.github.com/versions/,

yes, generally it is ok to follow GitHub Pages versions, but in practical terms this has no consequences, our sites are stored as plain html there, so they have nothing to do with GitHub Jekyll versions.

I will probably upgrade to 3.3 too, but now I'm quite busy with QEMU.

**Comment by carlosdelfino** [comment]
Ok, today I will review all the translation I have ever done (where possible).

So tomorrow I will continue my studies with QEMU.

Actually this change does not interfere much in the way you are working on the uOS site, but in workspace I have received the following error:

image

**Comment by ilg-ul** [comment]
> I have received the following error

no idea why. can it be related to the deprecated plug-in?

**Comment by carlosdelfino** [comment]
I do not think so.

I think the problem is in some url, redirect_to or redirect_from internally in some ".md"

**Comment by carlosdelfino** [comment]
About the jkeyll-last-modified-at plugin, this not work with Jekyll 3.3 I open a issue for this gjtorikian/jekyll-last-modified-at#44

**Comment by ilg-ul** [comment]
your ticket is a duplicate of: https://github.com/gjtorikian/jekyll-last-modified-at/issues/41

**Comment by carlosdelfino** [comment]
Different contexts. gjtorikian/jekyll-last-modified-at#41 is already resolved, need to release use with Jekyll 3.3.0 gjtorikian/jekyll-last-modified-at#44

**Comment by carlosdelfino** [comment]
I Closed in this versions:

```
source "https://rubygems.org"

gem 'jekyll', '=3.2.1', :platforms => [:ruby, :x64_mingw, :mswin]
gem 'wdm', '>= 0.1.0' if Gem.win_platform?

group :jekyll_plugins do
  gem 'jekyll-watch'
  gem 'jemoji'
  gem 'jekyll-paginate'
  gem 'jekyll-last-modified-at', '>=1.0.0',  :platforms => [:ruby, :x64_mingw, :mswin]
  gem 'jekyll-mentions', '=1.1.3',  :platforms => [:ruby, :x64_mingw, :mswin]
  gem 'jekyll-redirect-from', '=0.11.0',  :platforms => [:ruby, :x64_mingw, :mswin]
  gem 'jekyll-sitemap', '=0.11.0',  :platforms => [:ruby, :x64_mingw, :mswin]
  # gem 'jekyll-multiple-languages'
end
```

image

**Comment by carlosdelfino** [comment]
I thought about creating a gemfile group in order to force the versions into my environment, but I still do not understand how the bundler group system works.

However, as far as I understand, it is only possible use without a group and it is not possible to include a specific one with certain versions.

This will increase your work since every time I would have to execute the command including the key to delete my group `bundle update --without delfino` for example

**Comment by ilg-ul** [comment]
I have no idea why you have so many problems with your setup, mine was always functional, and I don't plan to spend much time changing it.

**Comment by carlosdelfino** [comment]
Well, I am reporting the problems and trying to suggest the solutions.

But you do not need to adopt them if you do not find it important.

I am always doing tests and changing the settings that brings me good knowledge about the medium I work with.

**Comment by ilg-ul** [comment]
> I am reporting the problems and trying to suggest the solutions

yes, please continue to report problems and suggest solutions.

**Pull request closed without merging**
