### PR TITLE
GitHub templates

### PR DESCRIPTION
**Pull request by carlosdelfino**
I left the files to pull request and comments created but empty.

Links related:
- https://github.com/blog/2111-issue-and-pull-request-templates
- https://help.github.com/articles/creating-an-issue-template-for-your-repository/
- https://github.com/blog/1375-task-lists-in-gfm-issues-pulls-comments

### CODE REVIEW

**Comment by ilg-ul** [comment]
I added the `.github/ISSUES_TEMPLATE.md` file. the `CONTRIBUTING.md` file is already present in the root folder, and I prefer it there, for visibility.

the pull request template is not yet there, since I have no idea what to write inside. any suggestions?

I'll add the Gemfile and Gemfile.lock files if you explain me why they are needed.

**Comment by carlosdelfino** [comment]
Well, do not command the ruby, I'm far from being a programmer in this language.

But as far as I went, the bundler creates a safe environment for both development and production, controlling the dependencies required for a successful implementation of the application.

In the case of Jykill can determine that used the exact gems that another programmer is using, so we can even specify the versions we want to use, avoiding unexpected results in each environment, since it will allow the application only usse specified in Gemfile

so that it goes well, you must first run the command:

`
bundler install
`

the update can also be good

`
bundler update
`

and then run the Jekyll for example:

`
bundler exec jekyll
`

Any other words, I'd be copying from the site: http://bundler.io/rationale.html

**Comment by carlosdelfino** [comment]
About the `.github`

I have not yet something that should be standard for informed and believe and describe the reason for the "pull_request" it would be nice to clearly identify which language.

**Comment by carlosdelfino** [comment]
I corrected the branchs.

**Comment by ilg-ul** [comment]
I added a simple PULL_REQUEST_TEMPLATE.md; we'll improve it with time.

I guess we can close this issue.

**Comment by carlosdelfino** [comment]
ok.
;)

**Pull request closed without merging**
