### PR TITLE
New articles approach

### PR DESCRIPTION
**Pull request by carlosdelfino**
## What/why?
Re created commit for new approach to make the list of articles and
posts.

With this new approach it is possible to create on-site articles such as
To make separate list of common posts. And vice versa.

The approach is useful to use with translation features as well.
  New-articles-approach

## How was it tested?

restart jekyll server or rebuild the site with new parameters

### CODE REVIEW

**Comment by carlosdelfino** [comment]
I'm sorry, I made the new branch based on the Portuguese branch, I'll be redoing it with the master branch.

**Comment by ilg-ul** [comment]
as you wish, but for the moment we'll not move articles to posts, there are already posts related to articles there.

**Comment by ilg-ul** [comment]
and be sure your Gemfile.lock file is portable, in the previous version I saw some versions related to mingw.

**Comment by carlosdelfino** [comment]
Actually keeping the gemfile.lock in the repository is not being good.

Whenever I update repository I need to rebuild it, it really is best to leave it out of the repository.

**Comment by ilg-ul** [comment]
> leave it out of the repository

ok, done.

**Comment by carlosdelfino** [comment]
I tried to make a new branch, but I do not understand what is keeping it connected to the old one, I have already re-built it based on its master and it insists on maintaining master-portuguese commits.

Anyway, There are resources that are useful for the internationalization of the site.

Even if more articles are added, thus unifying the process.

Do not think that I'm just being pushy, at this point the improvement relative to the translation is 100% integrated with the new feature of listing articles and posts.

If I prefer to rewrite the code, but it will only be rework, unless there are bugs, but send me the code as soon as possible...

**Pull request closed without merging**
