### PR TITLE
Code of conduct

### PR DESCRIPTION
**Pull request by carlosdelfino**
## What/why?

following instruction of http://contributor-covenant.org/ site.

### CODE REVIEW

**Comment by ilg-ul** [comment]
so the general recommendation is to add a CODE_OF_CONDUCT.md in the root of the project? and, in our case, a second one with the Portuguese translation?

yes, if needed, we can do this. 

apart from raising the number of files in the project root, I see a small problem with the need to provide an email address to report abuses. what addresses should we use?

**Comment by carlosdelfino** [comment]
Undoubtedly I believe that at least one file in English should exist on the site.

About the Portuguese version, if we (I) to translate at least the manual for this language, doubtless existed it and each new language that appears for each, I see it as as a way to welcome and clear rules to those who want contribute in your language.

And the root directory without a doubt is the best place.

On the e-mail, the English version is so me through what to put here and update and commit.

For the Portuguese version is allowing me to assume this responsibility.

**Comment by ilg-ul** [comment]
I added the English version of the CODE_OF_CONDUCT.md, in the project root, with my email address.

for the Portuguese version, if there will be other Portuguese speaking contributors, I think we should add a CONTRIBUTING.pt.md file, and with it we'll also add a CODE_OF_CONDUCT.pt.md.

until then, for you alone, I don't think we really need a separate file, you'll have no difficulties to abide by the English version. ;-)

**Comment by carlosdelfino** [comment]
I see the existence of the Portuguese version as a welcome sign for other employees.But there is no Preca in installing it.I leave this suggestion, I'll copy it to my branch in Portuguese so when we start to merge the branchs it goes along.What do you think?

**Comment by ilg-ul** [comment]
> What do you think?

I'm not sure I understand your suggestion.

as I said, if you think there will be many Portuguese speaking contributors, we'll add a `CONTRIBUTING.pt.md` file (or a `CONTRIBUINDO.md` file).

but for now I'm not sure we need anything more.

**Comment by carlosdelfino** [comment]
first of all I was trying to fix this branch and it was quite confusing, I'll redo it.

About file.

I think there's no hurry to put the code_of_conduct.pt.md file now, but would be a welcome sign.

However, neither the code_of_conduct.pt.md when contributting.pt.md there are important when new contributors in translation.

I leave the files by way of invitation to new contributors.

**Comment by ilg-ul** [comment]
> I was trying to fix this branch and it was quite confusing, I'll redo it.

no need to, I already applied most of the suggestions.

> code_of_conduct.pt.md

you do not need to translate it, it is already available in Portuguese in the original site.

**Comment by carlosdelfino** [comment]
Close this?

**Pull request closed without merging**
